=== choonchernlim/google-next-2023-transcripts/transcripts-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "keyPropertyMapping": "title"
    },
    "presentation_type": {
      "type": "string",
      "indexable": true,
      "searchable": true
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string",
        "keyPropertyMapping": "category"
      }
    },
    "transcript": {
      "type": "string",
      "keyPropertyMapping": "description"
    },
    "video_id": {
      "type": "string",
      "keyPropertyMapping": "uri"
    },
    "time": {
      "type": "string"
    }
  }
}

=== choonchernlim/google-next-2023-transcripts/transcripts/Opening Keynote: The New Way to Cloud (in 13min).json
{
    "title": "Opening Keynote: The New Way to Cloud (in 13min)",
    "presentation_type": "Snackables",
    "categories": [
        "AI and ML",
        "GENKEY-13M"
    ],
    "video_id": "ngb3g_Ktg4g",
    "time": "",
    "transcript": "[Music]hi everyone thanks for joining us forthis year's Cloud night in myconversations with Business Leaders overthe past few years have heard a similartheme they want a partner that's been onThe Cutting Edge of Technologybreakthroughs be it from desktop tomobile to the cloud or now to AIand a partner who can help navigate andLead through them we believe that makingAI helpful for everyone is the mostimportant way we'll deliver on ourmission in the next decade today we areusing generative AI to reimagine theexperience and take more of the work outof searching we call this the searchgenerative experience or SG for short weare pleased to be the first cloudprovider to any enable digitalwatermarking and verification for imagesgenerated on ourplatform our generative AI products aredelivering Real Results in every singlediscipline I'd like to take a moment tothank the many customers who areannouncing AI Innovations with us righthere atnext Google Cloud's World leadinginfrastructure delivers very high andpredictable performance unmatchedreliability and the very best securitywe offer this infrastructure in ourCloud regions in your data centers withGoogle distributed cloud and on the edgewe're announcing our TPUv5e a new highly efficient version manycustomers use Google kubernetes enginefor AI workloads today we're launching anew product gke Enterprise to enablemulticluster horizontal scaling withgpus and tpus we're announcing thegeneral availability of our A3 virtualmachines based on nvidia's latest h100acceleratedgpus A3 offers three times fastertraining 10 times greater networkingbandwidth than A2 ideal for incrediblydemanding AI workloads we're introducingthe titanium system a next generationtiered offload architecture thatunderpins the performance advances inour AI infrastructure we're announcingGeneral availability of the nextgeneration of Google distributed Cloudwhich supports stringent connectivitysovereignty and Regulatory needs we'reintroducing a brand new service crossCloud Network to allow you to centrallymanage secure and speed up applicationsacross all your clouds and SASproviders all of these announcementsoffer our customers breakthrough levelsof performance per dollar at the highestlevels of reliability and scale Morethan70% of generative AI unicorns are GoogleCloud customers it's the first timemachines are speaking in human languagewe partner with Google Cloud to get thebest inference we can to deploy thesemodels to the next generation of storycutters today we're announcing anexpanded partnership with envidia we'reintegrating serverless spark with Nvidiaacceleration libraries and Nvidia gpusfor data science work closed with dataproc our two companies with two of themost talented deepest computer scienceand Computing teams in the world arejoining forces to re reinvent Cloudinfrastructure for generative AI theamount of work that we're doing togetherin AI software is really incrediblewe're so excited about the work thatwe're doing we're going to put Nvidiadgx cloud in gcp that's greatyeah djx cloud is nvidia's AIsupercomputer this is where we do our AIresearch this is where we optimize ourincredible software stacks and all ofthis work that we do will instantlybenefit gcp and all the people that workon it Fox Sports has been partneringwith Google Cloud for 3 years to deliverInnovation for broadcasts like the World[Applause]Series Fox Sports has 1.9 million videosfrom games equal to over 27 paby of dataand continues to ingest tens ofthousands of hours of footage each monthwe can now search our archives usingnatural language to find relevant Clipsbuilding content for fans more quicklyand more easily thanever vertex AI is seeing very rapidgrowth in usage and new projects EsteLauder Companies uses gen to integratethe voice of the customer to driveproduct Innovation and improve theshopping[Music]experience with generative AI EST LauderCompanies Taps into social media andreviews to better understand evolvingpreferences across consumer groups theyleverage sentiment analysis to identifycustomer concerns and now they canrespond quickly to new beauty trends anddemand for new products today we'readding new models including metas llama2 tiis Falcon and pre-announcinganthropics Claw2 your data by which we mean input datametadata model outputs and humanfeedback is your data and no one else's[Music]good morning San Francisco so firstwe'll start with the model Garden wemade a promise to you that we were goingto add thirdparty models open- Sourcemodels with our first party models andso you can see our pre-announcement ofClaude 2 and meta's llama 2 right herein the vertex modelGarden so here's the big reveal inaddition to our native sources of publicweb content big query in Google CloudStorage today we announce jiraSalesforce and Confluence for Enterprisesearch andconversation when you use vertex there'sno drama with thisllama Six Flag is helping the 20 millionguests who visit their theme Parx eachyear have even more fun with the newdigital concer in theirrapall of this is made possible with vertexAi and our foundation models trained ondata pulled from the Six Flag websiteand multiplearchives workspace has been bringing themagic of AI to our users for almost adecade todaythousands of companies and over 1million people are already using duet AIduet has been helping customers writevisualize organize and connect likenever before and now all of thesecapabilities are available to you withtoday's GA launch of duet AI inworkspace where seeing more and morecustomers switch wholesale to Googleworkspace we are excited to expand our DAi and Google Cloud preview with newcapabilities with General availabilitycoming later this year duet goes furtherby providing you an expert assistantacross your entire software developmentlife cycle duet AI in AP makes it fastand easy to design create and publishyour apis with du AI in big query andlooker you can use both natural languageand autogenerate SQL Python and lookl toaccess and analyze your data and now youcan do all this within our new big queryStudio a unified interface for dataanalytics with server list notebooksallo Tob aai provides PG Vectorcompatible search that is up to 10 timesfaster than standard post press whatmakes Google Cloud unique is we delivera combination of three musthavecapabilities first we have Frontlineintelligence andexpertise second we we have a modernsecurity operations platform and thirdwe have an underlying Foundation of asecure Cloud platform securityoperations teams can now get threhunting on their chronical data bymandian experts who use our latestFrontline intelligence to expose attackor activity before it negatively impactsyour organizations Google Cloud had 75%fewer critical and high severityvulnerability since 2020 than one of themajor Cloud providers ERS and 60% fewervulnerabilities than the other majorcloudprovider I'm going to show you threeways that duet AI assists you in cybersecurity by generating AI summaries todescribe threats by searching forpatterns in your security data todetermine if you've been affected and byrecommending actions to take both inresponse to alerts but also toproactively improve security by closingdown attackpaths we're working with many SAScompanies to bring our generative AItechnology to transform every businessprocess one of our most importantPartners is workday we're also one oftheircustomers proud to say that workdayfinancial and hrr applications are nowlive on Google Cloud we can uh take jobdata job location and skills andbasically create a very strong jobdescription and I mean it's cont Tgeneration like so much of the genicases and it saves a ton of time usingGoogle AI again to uh to basicallybuild uh or leverage our skills APIwhich is an inference engine that thencustomers can build apps for retentionand upskilling in in this new world ofof skills which is where all of HR isgoing so it's just been great to do allthis co-innovationtogether we're working with other SAScompanies including box canva docus signas well as Jasper sap andmore we're also integrating ainfrastructure vertex Ai and big querywith infrastructure and platformPartners we have thousands of thirdpartydata sets available from industryleaders in our data and AI platformtoday we're announcing an expandedpartnership with Bloomberg to make theirdata available in our data and AI cloudand as system integrated part partnersare investing to build dedicatedpractices and train more than150,000 people on Google Cloudgenerative AI in closing we showed todaythe three most important ingredientsthat'll power this next chapter ofdigitaltransformation one our worldclassinfrastructure and platform for buildingAI two are always on collaborator duetAI to help you use AI in both workspaceand Google cloud and three ourinvestment in your success across allIndustries and business functionstogether with our broad partnerecosystem we appreciate being on thistransformation Journey withyou together we're building the new wayto[Applause]Cloudyeah"
}

=== choonchernlim/google-next-2023-transcripts/transcripts/Building a disability-inclusive culture and accessibility-first mindset.json
{
    "title": "Building a disability-inclusive culture and accessibility-first mindset",
    "presentation_type": "Breakout",
    "categories": [
        "IT Managers & Business Leaders",
        "DEI103"
    ],
    "video_id": "eddpv5DKG9k",
    "time": "Aug 30 01:45 PM - 02:30 PM CDT",
    "transcript": "foreign[Music]umnothingI'm only I amforeignmentioned my name is Danny Lynn I am aprogram manager working on internalMobility at Google specifically ourGoogle developer Academy programtraining non-technical googlers how tobe software Engineers my pronouns areshe herAya and for the purpose of thisconversation I identify as disabledbiracial and queerbefore we get too far into today'scontent we do want to create a sharedunderstanding a shared language and layout a few definitions so that you and usmight be on the same page together sofirst the intention of this conversationtoday is to begin by designing a companyculture of belonging for disabledemployees and their allies and unlockingthe potential to build a more inclusiveand accessible worldthat shared understanding is Guided byan understanding of what the wordsdisability and accessibility mean aswell as a few Associated thingsso throughout our conversation today wewill use the word disability in threecontexts first disability as a diagnosisthe medical model of disabilitysecond disability as a disabling set ofinteractions between person andenvironment which is the social model ofdisabilityand finally as a cultural identity oftenrepresented by a capital D which you'llsee throughout our slides todaydisability inclusion therefore is thepractice of ensuring an equitable andexcellent experience for people with anykind of disabilitiesand accessibility is an important aspectof disability inclusion it is thepractice of making informationactivities and or environments sensiblemeaningful and usable for as manydisabled people as possiblenow why does all of this matterfirst and most critically disabledrights are human rightsas while there are more than one billiondisabled people globally and this impactis magnet it's massive what isincremental for others is 10x fordisabled users like usover to Aubry for a conversation on whatthis means for your employeesum foreigninforeign[Music]taxESso when inflationum[Music]as well first timer and the science testumso awesomewell in Minnesota[Music]no no I also want to align with exampleAnthonyI'm still mad I'm looking at IunderstandoffumforeignsoforeignsoI'm doing the oil workplace when allthat is so inclusive that no one wouldever happenbut I think that was impossibleumand I want to understand how importantit is honorsoI thinknot only a client or opinionand today I'm not understand[Music]the second point abouton the floorum and I have been very fortunate timeand then a pointand I'm not here and then foreignEminemnoumand the third common here is that thisissothe topno morethat's important umand finallyit's not enoughnewsand that is a lot aboutumyou knowumno hand no no noI wasum the line is known in five monthsum and thenon time to the anniversary of theAmerican when this isadopted toum[Music]I'm not on the top of the floor anddownwindso with that we will transition totalking about your customers and I wantto start by anchoring on one simpletruth if your employees do not feelincluded and if your employees do nothave an accessible workplace it is notyet the time to turn towards yourcustomers however if it is time here aresome actions that you can take and Iwant to start with a reminder thatdisability only becomes a tragedy whenSociety fails to provide the thingsneeded to lead one's daily lifeconsider for a moment have you ever hadto make a phone call to solve a customerservice problema recent experience that I had reallyhighlights the impact of dual paths thatare not treated the sameso recently I had booked a trip to goawayand the company had a Black Friday salethree or four months after I booked thetrip they made it very clear in theirpromotions that if customers who hadpreviously booked a trip contacted themthey could take advantage of the BlackFriday pricing for me this meantthousands of dollars in savings for thistrip that I was planning to takethey had two paths to contact customersupport via phone and via emailphone was not accessible for me so Ireached out to them via email I includedmy trip information confirmation numberthe current pricing as seen in thepromotion and had done the math for themtoo on just how much I believed the costsavings wasshould be pretty straightforwardit took over a month to receive a replyvia email at which time the promotionwas over not to mention the email replydirected me to reach out to customerservice via phone and to be frankchastised me for having not having donesothis to the company seems like no bigdeal two Paths of customer support oneis faster one is slower it is what it isfor me this meant thousands of dollarsthat folks who were able to make a phonecall could take advantage of in savingsbut I could notthere are a number of customer serviceexperiences and broader company customerfacing experiences that are inaccessiblein similar ways it's not just phonecallsin-store experiences include the ofteninaccessibility of checkout linesproduct testing have you ever been in anelectronics store and tested a speakerthose speakers are capped at 70 of theirmaximum sound which sounds great intheory but if you have sensory concernseven 70 percent in an unenclosed spaceis a lot of noisefitting rooms and even the aisles in astore if you've ever been in a storewhen they're restocking their shelves inthe product to be restocked is in thecenter of the aisle that aisle is prettyhard to navigateas well Airline boarding is a greatexample of inaccessible experiencesbetween the experience of waiting inline the multiple points of failure thatwheelchair transfers experience andsunflower lanyards which we will comeback tofinally online tools many online toolshave overly complicated onboarding flowsthey are not just discouraging but alsooften inaccessibleburied accessibility tools so an onlinetool might have accessibility tools butthey are hard or unobvious to find orinaccessible customer support as in theexample I sharedso how do we evolve these experienceshow can we build for all usersespecially disabled usersfirst start by building for everydisabled person we must be comprehensivein creating access it is not enough tocreate a tool that tool needs to bebroadly accessible easily usable andeasily understoodyou must value disabled users feedbackand compensate for their time Aubrytalked about the advocacy labor tax ifyou're going to ask disabled users forfeedback or if a disabled user bringsyou feedback that you want to learn moreabout compensate for that timeand what is incremental for others is10x for us it is a massive impact tobuild this wayas well Solutions Aren't Enough let's goback to those sunflower lanyards for amoment if you're unfamiliar thesunflower lanyard program started a fewyears ago and offers a green lanyardwith bright yellow sunflowers that youcan get at any airport information deskacross the country and around the globethe intention of these lanyards is toprovide an indicator that the personwearing the lanyard has a hidden orvisible disabilitythe purpose of the lanyard is forairport and Airline staff to see thelanyard and immediately be aware thatthis individual may need support and tonot question their presence in placeshoweverif training is not comprehensive ifmessaging is unclear if training is notprovided in an ongoing basis theexperience faltersso if you've provided the messagingabout the sunflower lanyards to Airlineemployees and Airport employees one timethose folks are aware however dependenton labor turnover who's working on agiven day not everyone might know andthen you have the experience of anindividual with a hidden disabilitystanding in line waiting to pre-boardwearing their sunflower lanyard andbeing interrogated about their presencein that line because they otherwise lookvisibly able-bodied it is the continuityof the messaging in the follow-throughand follow up here that creates moreaccessible and inclusive experiencesa layer on top of this is executivesponsorship it is not enough for anexecutive to throw their weight behindthe launch of a programexecutive support is required toreaffirm commitment and importance ofprograms on an ongoing basis internaland external initiatives Need ExecutiveChampions not just for impact but alsofor follow throughso if you are an executive what actionsmight you takeFirst Take visible action and makepublicly available commitments examplesof this include the Google annualdiversity report and the 15 pledgecommit dollars not just words executivesponsorship with words Is frequent andhelpful but making meaningful headcountbudget product development and similarcommitments to disability andaccessibility work go a lot furtherand finally follow up on commitments andinitiatives by checking in you aresignaling to your employees that this isnot a one-time activity if employeesknow that an executive is going to befollowing up they are more likely tofollow through on the work as wellover to Aubrey for key lessons foreveryoneyeah oh I completely nothing more thanone for onething isan excellent experienceforeignforeign"
}

=== choonchernlim/google-next-2023-transcripts/transcripts/Daily Recap Day 1.json
{
    "title": "Daily Recap Day 1",
    "presentation_type": "Snackables",
    "categories": [
        "AI and ML",
        "EVENT-DAY1"
    ],
    "video_id": "Jj6PfCAQLUc",
    "time": "",
    "transcript": "hi everyone thanks for joining us forthis year's Cloud next we believe thatmaking AI helpful for everyone is themost important way we'll deliver on ourmission in the next decade[Music]we're now in the midst of one of themost profound technology shifts inhistoryour generative AI products aredelivering Real Results in every singlediscipline[Music]we appreciate being on thistransformation Journey with youtogether we're building the new way toCloud[Music]"
}

=== choonchernlim/google-next-2023-transcripts/transcripts/Wendy’s: Reinventing the Drive-Thru.json
{
    "title": "Wendy\u2019s: Reinventing the Drive-Thru",
    "presentation_type": "Snackables",
    "categories": [
        "AI and ML",
        "SC100"
    ],
    "video_id": "Qh3hrYfiwQQ",
    "time": "",
    "transcript": "hey everyone I'm Brenda Washington I'msuper excited to be at Google Cloud nextthis year let's learn what's next withAIWendy's oh yeah I think we're gonna goget some Wendy's I know you've been tothe drive-through a million times butdid you know in 1970 Wendy's actuallyinvented the modern drive-through andtoday they're ready to reinvent it let'ssee what we can order am I feeling aParmesan Caesar salad probably not let'sget to the real stuff over herepicklesstrawberry FrostyFrosty hundredsperfect how is this working like behindthe scenes every single order from ourcustomer is unique and truly theirs withour partnership with Google we saw anopportunity to use different Tech to doit differently to take this 200 billiondifferent options and just give it tothe large language model and have itfigure out how to do this thistechnology allows us to let them orderthe way they naturally would and get itright every single timecan you tell me a little bit about likewhat some of like the hardest problemsbringing AI into the Wendy'sdrive-through conversation is one of thehardest AI problems I know it's also oneof the most important withconversationally I we can bring thepower of technology to billions ofpeople who don't have to learn anythingnew they can interact with any kind ofTechnology including the right foot[Music]"
}

=== choonchernlim/google-next-2023-transcripts/transcripts/Google Cloud Next '23 Opening Keynote (in 4 min).json
{
    "title": "Google Cloud Next '23 Opening Keynote (in 4 min)",
    "presentation_type": "Snackables",
    "categories": [
        "AI and ML",
        "GENKEY-4M"
    ],
    "video_id": "LnIci9MwthM",
    "time": "",
    "transcript": "[Music]foreign[Music]thanks for joining us for this year'sCloud next we believe that making AIhelpful for everyone is the mostimportant way we'll deliver on ourmission in the next decade today we arepleased to be the first cloud providerto enable digital watermarking andverification for images generated on ourplatformproducts are delivering Real Resultsin every single discipline I'd like totake a moment to thank the manycustomers who are announcing AIInnovations with us right here at nextGoogle Cloud's World leadinginfrastructure delivers very high andpredictable performance unmatchedreliability and the very best securityall of these announcements offer ourcustomers breakthrough levels ofperformance per dollar at the highestlevels of reliability and scaleare two companies with two of the mosttalented deepest computer science andComputing teams in the world are joiningforces to reinvent Cloud infrastructurefor generative AI the amount of workthat we're doing together in AI softwareis really incredibleFox Sports has been partnering withGoogle Cloud for three yearsto deliver Innovation for broadcastslike the World Series[Applause]Fox Sports has 1.9 million videos fromgames equal to over 27 petabytes of dataand continues to ingest tens ofthousands of hours of footage each monthwe can now search our archives usingnatural language to find relevant Clipsbuilding content for fans more quicklyand more easily than everEstee Lauder companyuses gen AI to integrate the voice ofthe customer to drive product Innovationand improve the shopping experience[Music]foreignFlags is helping the 20 million guestswho visit their theme parks each yearhave even more fun with a new digitalConcierge in the wrapthis is made possible with vertex Ai andour foundation models trained on datapulled from the Six Flags website andmultiple archivesduet has been helping customers writevisualize organize and connect likenever beforeand now all of these capabilities areavailable to you with today's GA launchof duet Ai and workspacebut do what goes further by providingyou an expert assistant across yourentire software development life cycleGoogle Cloud had 75 percent fewercritical and high severity vulnerabilitysince 2020 than one of the major Cloudproviders and 60 percent fewervulnerabilities than the other majorcloud providerour partner ecosystem has over 100000 companiesproud to say that workday financial andHR applications are now live on GoogleCloud it's just been great to do allthis co-innovation togetherin closing we showed today the threemost important ingredients that willpower this next chapter of digitaltransformationone a world-class infrastructureplatform for building AItwo are always on collaborator duet AIto help you use AI in both workspace andGoogle Cloudand three our investment in your successacross all Industries and businessfunctions together with our broad pocketecosystem together we're building thenew way to Cloud[Music]"
}

=== choonchernlim/google-next-2023-transcripts/transcripts/Legacy Land.json
{
    "title": "Legacy Land",
    "presentation_type": "Snackables",
    "categories": [
        "AI and ML",
        "DEVKEY-HL"
    ],
    "video_id": "3t4jQxXvV5Y",
    "time": "",
    "transcript": "[Music]last night I dreamed about theGreenfieldwhere I could build whatever I wanted tono constraints or workarounds in thatMoment of Zen butmy pager woke me and I knewI'm living in a legacy land modernizingwhatever I can while the past is alwayschasing me we missed a payment on ourtechnical debt but we haven't defaultedyet we're gonna see if we can outentropyhere in Legacy land[Music]last week the bill server fell overagainit's leaking memory but hey ourwe're on an agile Journey someone tellme when we there I still see thewaterfallI found some code that caused mephysical painand ancient clues of sheer incompetency[Music]turns out the guy who made the mess wasme I'm living in a legacy land duct tapestuck to my sweaty hands and nothingseems ideal with weird Acquisitionscoming into the fold and temporary fixesthat are 10 years old but stillworshiping something realyou're in Legacy land remember thepeople who made those long ago technicaldecisions were doing the best with theresources they had and what they builtis still hereworked that's what Legacy means and wecelebrate that even as we work to makeit better[Music]nowwe're living in Legacy land it's messyand weird but on the other hand theesso's most of reality and slowly surelywhenever I do get done in something newwell if I'm lucky the best reward willbe a whole new Legacy[Music]I'm living in a legacy land"
}
