=== choonchernlim/google-next-2023-transcripts/transcripts-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "keyPropertyMapping": "title"
    },
    "presentation_type": {
      "type": "string",
      "indexable": true,
      "searchable": true
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string",
        "keyPropertyMapping": "category"
      }
    },
    "transcript": {
      "type": "string",
      "keyPropertyMapping": "description"
    },
    "video_id": {
      "type": "string",
      "keyPropertyMapping": "uri"
    },
    "time": {
      "type": "string"
    }
  }
}

=== choonchernlim/google-next-2023-transcripts/transcripts/Developer Keynote: What's Next for Your App? (All about AI).json
{
    "title": "Developer Keynote: What's Next for Your App? (All about AI)",
    "presentation_type": "Snackables",
    "categories": [
        "AI and ML",
        "DEVKEY-AI"
    ],
    "video_id": "6o1KGX-GaKs",
    "time": "",
    "transcript": "[Music]so I'm interested in Duet AI butparticularly duet AI in app sheet likehow can I automate with just those toolsthat's right so recall that duet AIwhich may who's heard the term duet AI atime or two at next so far a few of ushave it's our new generative AIcapability it's integrated into the coreof both Google workspace and GoogleCloud right and it can help you writecode analyze security threats and evendeveloplet's take kind of a gnarly use case andlet's see how far we can get into itusing just duet a and app sheet beforewe have to parachute out into some kindof custom code I wanted to easilycapture data using a phone or tablet soanyone in the school or on the shopfloor can initiate a report the safetyteam should have an operationaldashboard so they can track and escalateissues and we're going to want some helpfrom it to establish a method for AI toevaluate the pictures for specific areasto see if they are in compliance soundsgood so let me see if I can get thatinto a prompt that du I can use so Ineed to capture incident reports eachincident has a type status description adate and each incident should beassigned to what a team member right solet's put this in and see what happensnow I didn't exactly give duet AI anarchitecture diagram there so it's goingto be interesting to see how it thingsan app like this should be built andlook at this what it gave us is a coupleof tables so we've got a team memb tableand we've got an incidence table and aswe can see by this team member ID itseems to think there should be somerelationship between them so that seemscool we can click on this little pencilif we want to make changes to this butactually I think we can also do thatthrough chat can I just narrate it withmy voice that is a great use for anothercool thing we just Shi which isunstructured audio capture with duet AIso try this I want you to hit that plusbutton there all right and then hit theaudio button and we're going to see ifwe can just narrate this new incidentreport you don't have to like narrateexactly what's in each field which isgood cuz you can't actually see themright now just kind of tell duet more orless what you think should be in thisreport and we'll see if it can connectthe dots I mean as a developer withexisting workloads you're likely goingto have existing apis and LL models andand so on that you want to makeavailable to other parts of the businessand it turns out that app sheet lets youput a new front end on that stuff superquickly while staying in the Googleworkspace world of single sign on withfamiliar forms and such exactly so let'ssay that I've built an amazing vers TexAI Vision model to help identifypictures of workstations that are out ofcompliance actually let's not say thatlet's show it I actually have that appavailable right now it's built out in adifferent Google Cloud project um it'sbehind an apog API and it looks a littlesomething like this okay cool so you cansee some amazing uh developer stylinggoing on in that diagram but uh whatwe're looking at here is it's a a cloudrun service that uh fronts vertex AIit's going to run a few little uhprompts for us and then it's going tocome back asynchronously and call backto app sheet everyone say app sheet appsheet awesome all right okay save let'shit Y let's hit save all right and nowif you pop open this card here okay it'sgoing to take a second for vertex AI toread thispicture let's see if du AI in Cloudworkstations can uh help us write somecode excellent I'm a big fan of duet AIdoing autoc completion of code but alsoit can generate entire blocks of codehere for example you have a comment justfrom that we and generate all the codewe need to talk to postgress database toLoop through the rows and then to emaileach customer that has an abandoned cardlook my parents raised me right so I'malso going to add some test coverage tothis and so right from the IDE I canpick the operation or even do it rightfrom chat but I could pick the operationand say generate unit tests it'll jumpover to the DU AI chat right where wecan ask questions but'll also throw mesome unit tests which I can copy backinto my code run them and make goodchoices hereAI generated summary is actuallygenerated by du AI that's right yeah youmay remember this from the main keynoteyesterday but it's going to give us someverbiage about how we why it's not goodthat we have an admin service accountwith all these extra privileges butwatch this we can actually go deeperthan just a summary if I click on theattack score itself these attackexposure scores you'll see next to thesevulnerabilities now and that's justbased on WE rank these vulnerabilitiesas high medium or low concern we have anumeric score assigned to those you canactually configure that if you want uhbut you know a high is bad low score isgood it's like golf uh and if I click onthis number 21 here and select theorganization uh you should see somethingsuper cool which is our attack pathsimulation so let me zoom in on that soyou can see it a little bit better whatdo you think about that we are killingthis man anyway look at what jet isdoing here right it picked up a numberof things for us uh we've got a secureservice account key that's availablefrom the public internet I like theselittle red uh exclamation points herebecause it actually points to if we haveother um related vulnerabilities there'skind of this fractally integrated set ofproblems in our account we can kind ofexplore that in any dire it's likeChoose Your Own Adventure it's allmapped out for us here in this nicelittle attack path simulation and itbrings us all the way down to our demobucket which is where we have our buildlog stored so all that build metadata wewere creating before is actuallypotentially exposed right now and thisis a good note that we need to fix it souh yes that's uh that's where we're at II'll be honest I feel like my mind justmelted a little bit here one of mylongstanding forward wishing looklooking uh just goals for cloud overalljust say hey AI just tell me which ofthese containers have vulnerabilitieswhich policies are over permission andjust give me the steps to remediate themdon't make me guess don't make me puttogether a bunch of tools and it reallyfeels like we're starting to get therelet's see if you can get it to find likea specific type of safety incident likemaybe all the reports that say injury orsomething right CU I'm terrible atwriting sequel so when I can just giveit a comment and have it give me a querystatement that's uh that's make iteverybody better it'll also give me someoptions I might look and say that's notthe one I want or hey that looks closeall right let's pick that one run thatand what it should give me then I'mquerying that I'm getting only tworecords back because we have in injurysomewhere in that audio transcriptionwhich is awesome so when you're ready totake off your analyst hat and put onyour ml engineer hat what hat is that uhwe can switch over to vertexAI okay look at this this is the samenotebook so this is the same notebookwe're looking at can you callPalm can you extend that with vertex NEdo summarization from there yeah solet's let's actually invoke the Palm APIso we can summarize maybe that lengthysummary there and get back a nice littledescription that we can figure out whichfactories are a hotmess oh there we go I think you showedme the little magic wand button beforelook at that I like the wand you know itdoesn't take a lot to please me there wego and so if we come back we see there'sa summary I'm getting a single sentencesummary of what might be a really longtranscription and I'm doing all this inthe data frame again I'm not leaving mytool set[Music]w"
}

=== choonchernlim/google-next-2023-transcripts/transcripts/Developer Keynote: What's Next for Your App? (in 2min).json
{
    "title": "Developer Keynote: What's Next for Your App? (in 2min)",
    "presentation_type": "Snackables",
    "categories": [
        "Application Developers",
        "DEVKEY-2M"
    ],
    "video_id": "3MHHql1B7Ec",
    "time": "",
    "transcript": "[Music]welcome to Legacy land I'm living in alegacy land modernizing whatever I canwhile the past is alwaysexcited about this I brought an electricsousaphone did you forget yours or shemight be asking all right how do thesehelp me out in Legacy land automateeverything and if necessary use codethere's actually another really coolfeature that came out it's called CPUboosteveryone sayGoogle itself is actually turning 25years old at this little startup calledGoogle it was really hard to beat thebandwidth of a Honda full of hard driveswe have to simplify so you know we gotto talk about secure and got to talkabout security there was a zero dayvulnerability in a little open sourceJava Library called blog for Jay seemsidealevery fixes that are 10 years old butstill we're shipping shipping somethinghere in Legacy land but let's be realyour sling in containers your tweakingrelease pipelines this is a minorsecurity incident that happenedyesterday it's actually generated byduet AI here we go we've actually got anapp yay we just shipped a web and mobileapp and we mostly use natural languageright to describe it now we're ready tosee how the world of data is changing atesters I like to think of those kind oflike cryptographic Pokemon and I'm goingto collect those along the way thisspring my team wrapped up one of thebiggest data migrations in the historyof the planet here's where it gets fun Imean I can bring in data from ApacheIceberg now if I want to we always wantto make sure that we can buildexperiences that are more personalizedfor our customersI'm living in a legacy land everybodytake a minute to appreciate what justhappenedforeign"
}

=== choonchernlim/google-next-2023-transcripts/transcripts/Daily Recap Day 2.json
{
    "title": "Daily Recap Day 2",
    "presentation_type": "Snackables",
    "categories": [
        "AI and ML",
        "EVENT-DAY2"
    ],
    "video_id": "MdZ8lzTU7fw",
    "time": "",
    "transcript": "kubola is actually turning 25 this yearjust from Google Cloud can help us buildour next Legacyinterested in Duet AI but particularlyduet AI in app sheetsthis spring my team wrapped up one ofthe biggest data migrations in thehistory of the planetso you know we got to talk aboutsecurity got to talk about securityI always want to make sure that we canbuild experiences that are morepersonalized for our customers[Music]as a developer this is really getting mywheels turnedwe've got to put all that data to workbe able to use it using the power of AI[Music]I get so excited about this combinationof Open Source and managed toolingas efficiently and reliably as possible[Music]"
}

=== choonchernlim/google-next-2023-transcripts/transcripts/What’s next for application developers (in 5min).json
{
    "title": "What\u2019s next for application developers (in 5min)",
    "presentation_type": "Snackables",
    "categories": [
        "Application Developers",
        "SPTL201-5M"
    ],
    "video_id": "pZbX4Cgf3SY",
    "time": "",
    "transcript": "foreignbeing a cloud developer in 2023 it's atruly remarkable experience but whilegiving you all these excitingopportunities the fast evolvingtechnology landscape in the increasingnumber of cloud services have also ledto unprecedented levels of complexity atGoogle Cloud we're committed to helpingdevelopers we want to make your lifebetter by giving you a new way to Cloudthat is fast easy and secureso rather than burdening our developerswith an ever-growing set ofresponsibilities in the softwarelifecycle by shifting leftwe want to make your life easier byshifting down providing integratedassistance pre-configured automationsand out of the box security through ourplatform and through our managedservices and today I'm happy to announcethe general availability of jump startsolutions a new way to get you startedwith Google cloud with jumpstartSolutions you can quickly deploypre-built application and infrastructurebest practices into your Google Cloudaccountand can learn inside an interactiveenvironment right in the Google CloudWeb console today we have 14 jumpstartSolutions available in the Google Cloudconsole for you to pick from all ofthese Solutions are open source you canplay around with it customize it use itas a starting point to build your ownapplication you can also go check themout via the link here or find them inthe Google Cloud consoletalking about AI duet AI as you may allknow is the product that's designed totransform the way everyone works inGoogle Cloud we're now expanding theduet AI preview adding duet AIcapabilities across a wide range ofGoogle Cloud productsand assisting more Cloud users fordevelopers we introduce many newfeatures to the dwet AI preview inaddition to features like codecompletion and code generation you'llNow find duet AI chat assistance in manyGoogle Cloud products we've alsointroduced smart actions which allow youto perform contextual AI powered actionslike code explanation and testgenerationand to support your compliance needs interms of licensing requirements duetaiprovides Source citations now duet AItoday supports more than 20 programminglanguages and thanks to Cloud code youcan also use duet AI in many popularIdes duet AI is also available in apogeeAPI management now in apogee duetai cando things like help developers build APIspecifications from simple naturallanguage prompts if you'd like to learnmore about all the exciting developercapabilities of duet AI please visitthis duet AI webpage cloud.google.comduet-aianother aspect of enabling differentapplication components to work togetherwhat we call integration today we areextending our integration services toinclude application integration a newplatform designed to help you automateapp to app Communications across bothGoogle cloud and third-party softwarewithout the need for complex coding orconfigurations in recent years you knowas an example with the rising trend ofremote and hybrid working companies arehiring more developers that are widelydispersed which can lead to increasingsecurity concerns it can also cause slowdeveloper onboarding and reducedevelopment productivity now to helpaddress these challenges we introducedCloud workstations last year at Dexwhich successfully went into GA recentlybesides Cloud workstationsanother example of us shifting securitydown is around software supply chainsecurity to help Google Cloud customerswho are using many of our partnerSolutions in their software deliverycycle today I'm thrilled to announce ourexpanded partnership with gitlab now letme welcome David DeSanto Chief productofficer from gitlab onto the stage Davidgitlab and Google Cloud are partneringto provide a seamless devsecopsexperience allowing you to bringsoftware supply chain security to theForefront of how you build software thispartnership delivers an end-to-endapplication development experience thatis deeply integrated together providingyou Best in Class reliability efficiencyand security end to end we're going tocontinue to work on this and if you wantto know more please sign up you can scanand you'll get updates thank you all andback you Gabe thank you again to uh youknow for everyone for attending thissession in this AI driven world Googlecloud is committed to helping Developersby shifting down instead of Shiftingleft we want to give you a new way toCloud that is fast easy and secure[Music]"
}
